apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: appscode-voyager
  name: appscode-voyager
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: appscode-voyager
  template:
    metadata:
      labels:
        run: appscode-voyager
    spec:
      containers:
      - args:
        - --cloud-provider={{}}
        - --cluster-name{{}}
        image: appscode/voyager:1.5.0
        imagePullPolicy: Always
        name: appscode-voyager