apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: voyager
  name: voyager-operator
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: voyager
    spec:
      containers:
      - name: voyager
        args:
        - run
        - --v=3
        - --cloud-provider=minikube
        - --cloud-config=
        - --ingress-class=
        - --custom-templates=/srv/voyager/custom/*.cfg
        image: appscode/voyager:3.2.0-rc.3
        ports:
        - containerPort: 56790
          name: http
          protocol: TCP
        volumeMounts:
          - mountPath: /etc/kubernetes
            name: cloudconfig
            readOnly: true
          - mountPath: /srv/voyager/custom
            name: templates
            readOnly: true
      volumes:
        - hostPath:
            path: /etc/kubernetes
          name: cloudconfig
        - configMap:
            name: voyager-templates
          name: templates
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: voyager
  name: voyager-operator
  namespace: kube-system
spec:
  ports:
  - name: http
    port: 56790
    targetPort: http
  selector:
    app: voyager
