apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        app: "{{ template "name" . }}"
        heritage: "{{ .Release.Service }}"
        release: "{{ .Release.Name }}"
    spec:
{{- if .Values.rbac.install }}
      serviceAccountName: {{ template "fullname" . }}
{{- end }}
      containers:
      - args:
        - run
        - --cloud-provider={{ .Values.cloudProvider }}
        - --cloud-config={{ .Values.cloudConfig }}
        - --v={{ .Values.logLevel }}
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        name: voyager
        env:
          - name: OPERATOR_SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName
        ports:
        - containerPort: 56790
          name: http
          protocol: TCP
{{- if .Values.persistence.enabled }}
        volumeMounts:
          - mountPath: {{ dir .Values.cloudConfig | quote }}
            name: cloudconfig
            readOnly: true
      volumes:
        - hostPath:
            path: {{ .Values.persistence.hostPath | quote }}
          name: cloudconfig
{{- end -}}
